### ISSUE TITLE
Porting/core-cpan-diff not detecting more recent upstream versions of cpan distros

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19981]
Today I was amusing myself by watching @atoomic prepare the monthly dev release.  As part of that amusement I ran `perl Porting/core-cpan-diff --all -o out` and examined the output file.  The program logged this information:
```
PerlIO::via::QuotedPrint - SHAY/PerlIO-via-QuotedPrint-0.09.tar.gz
  upstream is: cpan

```
Then I noticed that @atoomic had filed a pull request to synchronize core with upstream version 0.10.  I checked [upstream](https://metacpan.org/pod/PerlIO::via::QuotedPrint) and, sure enough, this distribution has been at version 0.10 on CPAN since May 22.

That suggests that there's either a defect in `Porting/core-cpan-diff` or I'm misunderstanding something about its use.  Insights?

**Comment by atoomic** [comment]
I ran: `./perl -Ilib Porting/core-cpan-diff -x -a` which was returning this at the beginning of the day

```
bignum:
    Perl: PJACKLAM/bignum-0.65.tar.gz
    CPAN: PJACKLAM/bignum-0.66.tar.gz

Compress::Raw::Bzip2:
    Perl: PMQS/Compress-Raw-Bzip2-2.103.tar.gz
    CPAN: PMQS/Compress-Raw-Bzip2-2.201.tar.gz

Compress::Raw::Zlib:
    Perl: PMQS/Compress-Raw-Zlib-2.105.tar.gz
    CPAN: PMQS/Compress-Raw-Zlib-2.202.tar.gz

CPAN:
    Perl: ANDK/CPAN-2.33-TRIAL.tar.gz
    CPAN: ANDK/CPAN-2.34.tar.gz

DB_File:
    Perl: PMQS/DB_File-1.857.tar.gz
    CPAN: PMQS/DB_File-1.858.tar.gz

experimental:
    Perl: LEONT/experimental-0.027.tar.gz
    CPAN: LEONT/experimental-0.028.tar.gz

Filter::Util::Call:
    Perl: RURBAN/Filter-1.60.tar.gz
    CPAN: RURBAN/Filter-1.61.tar.gz

IO-Compress:
    Perl: PMQS/IO-Compress-2.106.tar.gz
    CPAN: PMQS/IO-Compress-2.201.tar.gz

libnet:
    Perl: SHAY/libnet-3.13.tar.gz
    CPAN: SHAY/libnet-3.14.tar.gz

Locale::Maketext:
    Perl: TODDR/Locale-Maketext-1.29.tar.gz
    CPAN: TODDR/Locale-Maketext-1.31.tar.gz

Math::BigInt:
    Perl: PJACKLAM/Math-BigInt-1.999830.tar.gz
    CPAN: PJACKLAM/Math-BigInt-1.999837.tar.gz

Math::BigInt::FastCalc:
    Perl: PJACKLAM/Math-BigInt-FastCalc-0.5012.tar.gz
    CPAN: PJACKLAM/Math-BigInt-FastCalc-0.5013.tar.gz

Math::BigRat:
    Perl: PJACKLAM/Math-BigRat-0.2621.tar.gz
    CPAN: PJACKLAM/Math-BigRat-0.2624.tar.gz

PerlIO::via::QuotedPrint:
    Perl: SHAY/PerlIO-via-QuotedPrint-0.09.tar.gz
    CPAN: SHAY/PerlIO-via-QuotedPrint-0.10.tar.gz

Pod::Checker:
    Perl: MAREKR/Pod-Checker-1.74.tar.gz
    CPAN: MAREKR/Pod-Checker-1.75.tar.gz

Pod::Usage:
    Perl: ATOOMIC/Pod-Usage-2.01.tar.gz
    CPAN: MAREKR/Pod-Usage-2.03.tar.gz

Test::Simple:
    Perl: EXODIST/Test-Simple-1.302190.tar.gz
    CPAN: EXODIST/Test-Simple-1.302191.tar.gz

Text::Balanced:
    Perl: SHAY/Text-Balanced-2.04.tar.gz
    CPAN: SHAY/Text-Balanced-2.06.tar.gz

Win32:
    Perl: JDB/Win32-0.58.tar.gz
    CPAN: JDB/Win32-0.59.tar.gz

```
