### ISSUE TITLE
Installing CPAN modules for a custom Perl install with `installprefix` different from `prefix`

### ISSUE THREAD

**Issue by vadimkantorov** [Perl/perl5#22875]
I'm building a custom Perl install which includes:
1. a Perl with all modules built statically
2. CPAN-installed modules, including build time dependences for (3) - (having to install using `cpan` after Perl build because of https://github.com/Perl/perl5/issues/22786)
3. Some custom-built modules - which I need to be built statically, so having to extract from tarballs and build them statically manually

After steps (1)-(2)-(3) my custom Perl build should be complete and not modified any further.

Another peculiarity is that I'm building this Perl build in order to make it available at run time in some path like `/opt/myperlprefix` (but this path is not available at build time), so I thought I'd use `-Dprefix=/opt/myperlprefix` and `-Dinstallprefix` set to some path existing at build time.

(1) passes well, but (2) fails badly. The first problem is that (2) tries to use `prefix` and does not use at all `installprefix` for module search, so I had to provide `PERLLIB` and `CPATH` to make `installprefix` discoverable. But then it produces `NOT OK` and nasty warning messages during the modules' build time.

If I don't use a separate `installprefix != prefix`, all works well.

How could I properly prepare such a perl install? E.g. if I don't use a separate `installprefix`, how can I redefine INC after the install? (i.e. I'd like that after my build setup and perl install is complete, only `/opt/myperlprefix` is used for module search path) If it's not possible, how to properly run `cpan` to make the Perl build fully discoverable without sketchy patches using `PERLLIB` / `CPATH`? (and currently `cpan` produces NOT OK anyway)

Thanks!

[log_cpan.txt](https://github.com/user-attachments/files/18256330/log_cpan.txt)

My GitHub Actions workflow file, using Ubuntu and Alpine:

```yaml
name: bug

on: workflow_dispatch
env:
  PERLVER: "5.40.0"
  URLPERL: https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz

jobs:
  bug:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils gdb cmake git xz curl gperf p7zip zip autoconf automake libtool pkgconfig gnupg libxml2-dev libxslt-dev expat-dev openssl-dev openssl  zlib-static expat-static wget

      - uses: actions/checkout@v4

      - name: Install Perl static
        shell: bash
        run: |
          export PERLINSTALLPREFIX=$RUNNER_WORKSPACE/myperlinstallprefix
          export PERLPREFIX=/opt/myperlprefix
          #export PERLPREFIX=$PERLINSTALLPREFIX # starts with /__w/
          export LD_LIBRARY_PATH=$PERLINSTALLPREFIX/lib:$LD_LIBRARY_PATH

          mkdir perlsourcestatic && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=perlsourcestatic
          export BUILD_ZLIB=0
          cd perlsourcestatic && sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="$PERLPREFIX" -Dinstallprefix="$PERLINSTALLPREFIX" -Dusedevel -Uversiononly -Dlibs="-lpthread -ldl -lm -lutil -lc /lib/libz.a" -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode" && cd -
          make -C perlsourcestatic
          make -C perlsourcestatic install

          export PERLLIB=$PERLINSTALLPREFIX/lib/$PERLVER:$PERLINSTALLPREFIX/lib/$PERLVER/x86_64-linux:$PERLINSTALLPREFIX/lib/site_perl/$PERLVER
          export CPATH=$PERLINSTALLPREFIX/lib/$PERLVER/x86_64-linux/CORE
          # added Config::AutoConf to the next line and now it fails with NOT OK
          $PERLINSTALLPREFIX/bin/perl $PERLINSTALLPREFIX/bin/cpan -T Alien::Base::Wrapper Alien::Build Alien::Build::MM Alien::cmake3 Alien::Libxml2 inc::Module::Install Module::Implementation Config::AutoConf
```
